[build-system]
requires = ["maturin>=1.7,<2"]
build-backend = "maturin"

[project]
name = "uoe-ms-auth"
version = "0.1.0"
description = "University of Edinburgh SAML bindings"
readme = "README.md"
requires-python = ">=3.9"

[project.urls]
Repository = "https://github.com/platinumxy/uoe-ms-auth"
Issues = "https://github.com/platinumxy/uoe-ms-auth/issues"

[tool.maturin]
bindings = "pyo3"
module-name = "uoe_ms_auth"